<?xml version="1.0" encoding="utf-8"?><Database Name="dziennikucznia.studentlive.pl" Class="linqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=clea.mic.psnc.pl;Initial Catalog=dziennikucznia.studentlive.pl;Persist Security Info=True;User ID=dziennikucznia" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dziennikucznia_studentlive_plConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Problems" Member="Problems">
    <Type Name="Problem">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProblemsCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Languages" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DifficultyLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OpeningDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClosingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeLimit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SizeLimit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Input" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Output" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>